# Generated by Django 3.2a1 on 2022-07-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=5000)),
            ],
        ),
    ]
