# Generated by Django 3.2a1 on 2022-07-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20220719_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Subject',
            field=models.CharField(blank=True, default='Customer Query', max_length=100),
        ),
    ]
