# Generated by Django 3.2a1 on 2022-07-27 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=250, unique=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='brand_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.brand'),
        ),
    ]
