# Generated by Django 4.0.6 on 2022-08-12 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('to_state', models.CharField(choices=[('NI', 'Niger'), ('BO', 'Borno '), ('TA', 'Taraba'), ('KD', 'Kaduna'), ('BA', 'Bauchi'), ('YO', 'Yobe'), ('ZA', 'Zamfara'), ('AD', 'Adamawa'), ('KW', 'Kwara'), ('KE', 'Kebbi'), ('BE', 'Benue'), ('PL', 'Plateau'), ('KO', 'Kogi'), ('OY', 'Oyo'), ('NA', 'Nasarawa'), ('SO', 'Sokoto'), ('KT', 'Katsina'), ('JI', 'Jigawa'), ('CR', 'Cross River'), ('KN', 'Kano'), ('GO', 'Gombe'), ('ED', 'Edo'), ('DE', 'Delta'), ('OG', 'Ogun'), ('ON', 'Ondo'), ('RI', 'Rivers'), ('BY', 'Bayelsa'), ('OS', 'Osun'), ('FC', 'Fct'), ('EN', 'Enugun'), ('AK', 'Akwa Ibom'), ('EK', 'Ekit'), ('AB', 'Abia'), ('EB', 'Ebonyi'), ('IM', 'Imo'), ('AN', 'Anambra'), ('LA', 'Lagos')], max_length=10)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('To_agree', models.BooleanField(default=False, verbose_name='Car is Booked')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
